package com.starfish.kol.android.util.listbuilders;

import android.text.Html;
import android.view.View;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.android.util.adapters.ListElementBuilder;
import com.starfish.kol.model.models.chat.ChatText;

public class ChatBuilder implements ListElementBuilder<ChatText> {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -26427334589L;

	@Override
	public int getChildLayout() {
		return R.layout.list_chat_item;
	}


	@Override
	public void fillChild(View view, ChatText child) {
		TextView text = (TextView)view.findViewById(R.id.list_chat_text);
		text.setText(Html.fromHtml(child.getText()));
	}
}
