package com.starfish.kol.android.util.listbuilders;

import android.text.Html;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.android.util.ImageDownloader;
import com.starfish.kol.android.util.adapters.ListFullBuilder;
import com.starfish.kol.model.interfaces.ModelGroup;
import com.starfish.kol.model.interfaces.ModelItem;

public class DefaultBuilder<F extends ModelItem> implements ListFullBuilder<ModelGroup<F>, F>{	
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 5342305049138777557L;

	@Override
	public int getGroupLayout() {
		return R.layout.list_generic_header;
	}

	@Override
	public int getChildLayout() {
		return R.layout.list_generic_item;
	}

	@Override
	public void fillGroup(View view, ModelGroup<F> group) {
		TextView text = (TextView)view.findViewById(R.id.list_header_text);
		text.setText(group.getName());
	}

	@Override
	public void fillChild(View view, F child) {
		TextView text = (TextView)view.findViewById(R.id.list_item_text);
		text.setText(Html.fromHtml(child.getText()));
		
		ImageView img = (ImageView)view.findViewById(R.id.list_item_image);
		if(child.getImage() == null || child.getImage().length() == 0) {
			img.setVisibility(View.GONE);
		} else {
			img.setVisibility(View.VISIBLE);
			ImageDownloader.loadFromUrl(img, child.getImage());
		}
	}

}
