package com.starfish.kol.android.util.listbuilders;

import android.graphics.Color;
import android.view.View;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.model.models.skill.SkillModelElement;

public class SkillsBuilder extends SubtextBuilder<SkillModelElement> {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -8256923287045711869L;
	

	@Override
	public void fillChild(View view, SkillModelElement child) {
		super.fillChild(view, child);

		TextView text = (TextView) view.findViewById(R.id.list_item_text);
		if(child.getIsDisabled()) {
			text.setTextColor(Color.LTGRAY);
		} else {
			text.setTextColor(Color.BLACK);
		}
	}
}
