package com.starfish.kol.android.util.listbuilders;

import android.text.Html;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.android.util.adapters.ListFullBuilder;
import com.starfish.kol.model.elements.interfaces.ModelGroup;

public class TextBuilder<F> implements ListFullBuilder<ModelGroup<F>, F>{	
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 643873892355245762L;

	@Override
	public int getGroupLayout() {
		return R.layout.list_generic_header;
	}

	@Override
	public int getChildLayout() {
		return R.layout.list_generic_item;
	}

	@Override
	public void fillGroup(View view, ModelGroup<F> group) {
		TextView text = (TextView)view.findViewById(R.id.list_header_text);
		text.setText(group.getName());
	}

	@Override
	public void fillChild(View view, F child) {
		TextView text = (TextView)view.findViewById(R.id.list_item_text);
		text.setText(Html.fromHtml(child.toString()));
		
		ImageView img = (ImageView)view.findViewById(R.id.list_item_image);
		img.setVisibility(View.GONE);
	}
}
