package com.github.kolandroid.kol.android.controllers.web;


import android.view.View;

import com.github.kolandroid.kol.android.R;
import com.github.kolandroid.kol.android.controller.LinkedModelController;
import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.android.screen.ScreenSelection;
import com.github.kolandroid.kol.android.screen.ViewScreen;
import com.github.kolandroid.kol.model.LiveModel;
import com.github.kolandroid.kol.model.models.LiveWebModel;

public class LiveWebController extends
        LinkedModelController<LiveModel.LiveMessage, LiveWebModel> {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = -7994839681352351331L;

    private WebController web;

    public LiveWebController(LiveWebModel model) {
        super(model);
    }

    @Override
    public int getView() {
        return R.layout.fragment_crafting_subscreen;
    }

    @Override
    public void chooseScreen(ScreenSelection choice) {
        choice.displayPrimary(this, false);
    }

    @Override
    public void connect(View view, LiveWebModel model, Screen host) {
        if (web == null) {
            web = new WebController(model.getBaseModel());
        }
        ViewScreen screen = (ViewScreen) view;
        screen.display(web, host);
    }

    @Override
    public void receiveProgress(View view, LiveWebModel model, LiveModel.LiveMessage message, Screen host) {
        if (web != null)
            web.updateModel(model.getBaseModel());
    }
}
