package com.starfish.kol.model.models.skill;

import com.starfish.kol.connection.Session;
import com.starfish.kol.model.elements.OptionElement;
import com.starfish.kol.model.elements.basic.BasicAction;
import com.starfish.kol.model.elements.basic.BasicSubtextElement;
import com.starfish.kol.model.elements.interfaces.DeferredGameAction;
import com.starfish.kol.model.elements.interfaces.MultiUseableItem;
import com.starfish.kol.util.Regex;

public abstract class SkillModelElement extends BasicSubtextElement {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 4550357750709654161L;

	private static final Regex OPTION_MP = new Regex("\\(.*?\\)", 0);

	private final boolean disabled;

	protected SkillModelElement(OptionElement option) {
		this(option, OPTION_MP.extractSingle(option.text, ""));
	}

	private SkillModelElement(OptionElement option, String extractedSubtext) {
		super(OPTION_MP.replaceAll(option.text, ""), option.img,
				extractedSubtext);

		this.disabled = option.disabled;
	}

	public boolean getIsDisabled() {
		return disabled;
	}

	public abstract void select(SkillModelVisitor visitor);

	public static class Skill extends SkillModelElement implements
			MultiUseableItem {
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 2545384161227586658L;

		protected final String actionBase;
		protected final Session session;

		public Skill(Session session, OptionElement option, String pwd) {
			super(option);

			this.actionBase = "skills.php?pwd=" + pwd
					+ "&action=Skillz&whichskill=" + option.value;
			this.session = session;
		}

		@Override
		public void select(SkillModelVisitor visitor) {
			visitor.display(this);
		}

		@Override
		public DeferredGameAction use(String number) {
			return new BasicAction(session, actionBase + "&quantity=" + number);
		}
	}

	public static class Buff extends SkillModelElement {
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 657436834573234L;

		protected final String actionBase;
		protected final Session session;

		public Buff(Session session, OptionElement option, String pwd,
				String yourself) {
			super(option);

			String action = "skills.php?pwd=" + pwd;
			action += "&action=Skillz&targetplayer=" + yourself;
			action += "&whichskill=" + option.value;
			this.actionBase = action;
			this.session = session;
		}

		@Override
		public void select(SkillModelVisitor visitor) {
			visitor.display(this);
		}

		public DeferredGameAction cast(String number, String onPlayer) {
			String action = actionBase;
			action += "&specificplayer=" + onPlayer;
			action += "&bufftimes=" + number;
			return new BasicAction(session, action);
		}
	}

	public static class RestorerItem extends SkillModelElement implements
			MultiUseableItem {
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 2931087678941136636L;

		private final String actionBase;
		private final Session session;

		public RestorerItem(Session session, OptionElement option, String pwd) {
			super(option);

			this.session = session;

			String action = "inv_use.php";
			action += "?pwd=" + pwd;
			action += "&action=useitem&bounce=skills.php%3Faction%3Duseditem";
			action += "&whichitem=" + option.value;
			this.actionBase = action;
		}

		public DeferredGameAction use(String quantity) {
			String action = actionBase + "&itemquantity=" + quantity;
			return new BasicAction(session, action);
		}

		@Override
		public void select(SkillModelVisitor visitor) {
			visitor.display(this);
		}
	}
}