package com.github.kolandroid.kol.android.controller;

import android.view.View;

import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.android.util.HandlerCallback;
import com.github.kolandroid.kol.model.LinkedModel;

public abstract class LinkedModelController<C, M extends LinkedModel<C>> extends ModelController<M> {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 5761904333216584549L;

    private transient HandlerCallback<C> callback;

    public LinkedModelController(M model) {
        super(model);
    }

    @Override
    public void connect(final View view, final Screen host) {
        if (callback != null) {
            callback.close();
        }

        this.callback = new HandlerCallback<C>() {
            @Override
            public void receiveProgress(C message) {
                LinkedModelController.this.receiveProgress(view, getModel(), message, host);
            }
        };

        getModel().attachCallback(callback.weak());
        super.connect(view, host);
    }

    public abstract void receiveProgress(View view, M model, C message, Screen host);

    @Override
    public void disconnect(Screen host) {
        if (callback != null) {
            callback.close();
        }
    }
}
