package com.github.kolandroid.kol.android.controller;

import android.view.View;

import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.model.Model;

public abstract class ModelController<M extends Model> implements Controller {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 5761904333216584549L;

    private M model;

    public ModelController(M model) {
        this.model = model;
    }

    @Override
    public void attach(final View view, final Screen host) {
        this.model.attachView(host.getViewContext());
        this.attach(view, model, host);
    }

    public abstract void attach(View view, M model, Screen host);

    @Override
    public void connect(final View view, final Screen host) {
        this.connect(view, model, host);
    }

    public void connect(View view, M model, Screen host) {
        // Do nothing by default
    }

    @Override
    public void disconnect(Screen host) {
        // do nothing
    }

    public M getModel() {
        return model;
    }

    protected void setModel(M model) {
        this.model = model;
    }
}
