package com.github.kolandroid.kol.android.controller;

import android.support.annotation.CallSuper;
import android.view.View;

import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.model.Model;
import com.github.kolandroid.kol.util.Logger;

import java.lang.ref.WeakReference;

public abstract class UpdatableModelController<M extends Model> extends ModelController<M> implements UpdatableController {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 8000096303272331462L;

    private transient WeakReference<Screen> currentScreen;
    private transient WeakReference<View> currentView;

    public UpdatableModelController(M model) {
        super(model);

        this.currentView = new WeakReference<>(null);
        this.currentScreen = new WeakReference<>(null);
    }

    @CallSuper
    @Override
    public void connect(View view, Screen host) {
        super.connect(view, host);
        this.currentView = new WeakReference<>(view);
        this.currentScreen = new WeakReference<>(host);
    }

    @CallSuper
    @Override
    public void disconnect(Screen host) {
        super.disconnect(host);
        this.currentView = new WeakReference<>(null);
        this.currentScreen = new WeakReference<>(null);
    }

    protected void doReplace(M model) {
        if (currentView == null || currentScreen == null) {
            return;
        }

        View view = currentView.get();
        Screen screen = currentScreen.get();
        if (view != null && screen != null) {
            disconnect(screen);
            attach(view, screen);
            connect(view, screen);
            view.invalidate();
        }
    }

    @Override
    public <F> boolean tryApply(Class<F> type, F object) {
        Logger.log("UpdatableModelController", "Update: " + type + ", Current: " + getModel().getClass());
        if (getModel().getClass().equals(type)) {
            M newModel = (M) object;
            this.setModel(newModel);
            doReplace(newModel);
            return true;
        }
        return false;
    }
}
