package com.github.kolandroid.kol.android.controller;

import android.view.View;

import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.model.Model;

import java.lang.ref.WeakReference;

public abstract class UpdatableModelController<M extends Model> extends ModelController<M> implements UpdatableController<M> {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 8000096303272331462L;

    private transient WeakReference<Screen> currentScreen;
    private transient WeakReference<View> currentView;

    public UpdatableModelController(M model) {
        super(model);

        this.currentView = new WeakReference<>(null);
        this.currentScreen = new WeakReference<>(null);
    }

    @Override
    public void connect(final View view, final Screen host) {
        this.currentView = new WeakReference<>(view);
        this.currentScreen = new WeakReference<>(host);

        super.connect(view, host);
    }

    @Override
    public void disconnect(Screen host) {
        super.disconnect(host);

        this.currentView = new WeakReference<>(null);
        this.currentScreen = new WeakReference<>(null);
    }

    public void updateModel(M model) {
        this.setModel(model);

        View view = currentView.get();
        Screen screen = currentScreen.get();
        if (view != null && screen != null) {
            connect(view, screen);
        }
    }
}
