package com.github.kolandroid.kol.model;

import com.github.kolandroid.kol.connection.Session;
import com.github.kolandroid.kol.model.GroupModel.ChildModel;

public abstract class GroupModel<Child extends ChildModel> extends Model {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 8057138180603838561L;

    public GroupModel(Session s) {
        super(s);
    }

    public abstract int getActiveChild();

    public abstract Child[] getChildren();

    public interface ChildModel {
        String getTitle();
    }
}
