package com.github.kolandroid.kol.android.binders;

import android.text.Html;
import android.view.View;
import android.widget.TextView;

import com.github.kolandroid.kol.android.R;
import com.github.kolandroid.kol.model.models.chat.ChatText;

import java.io.Serializable;

public class ChatBinder implements Binder<ChatText>, Serializable {
    public static final ChatBinder ONLY = new ChatBinder();
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 3303232279575856149L;

    private ChatBinder() {

    }

    @Override
    public int getView() {
        return R.layout.chat_message_view;
    }

    @Override
    public void bind(View view, ChatText model) {
        TextView text = (TextView) view.findViewById(R.id.list_chat_text);
        text.setText(Html.fromHtml(model.getText()));
    }

}
