package com.github.kolandroid.kol.android.binders;

import android.graphics.Color;
import android.view.View;
import android.widget.TextView;

import com.github.kolandroid.kol.android.R;
import com.github.kolandroid.kol.model.models.skill.SkillModel;

import java.io.Serializable;

public class SkillsBinder implements Binder<SkillModel>, Serializable {
    public static final SkillsBinder ONLY = new SkillsBinder();
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = -8682660437814936698L;

    private SkillsBinder() {

    }

    @Override
    public int getView() {
        return SubtextBinder.ONLY.getView();
    }

    @Override
    public void bind(View view, SkillModel model) {
        SubtextBinder.ONLY.bind(view, model);

        TextView text = (TextView) view.findViewById(R.id.generic_element_text);
        if (model.getDisabled()) {
            text.setTextColor(Color.LTGRAY);
        } else {
            text.setTextColor(Color.BLACK);
        }
    }

}
