package com.github.kolandroid.kol.android.binders;

import android.text.Html;
import android.view.View;
import android.widget.TextView;

import com.github.kolandroid.kol.android.R;
import com.github.kolandroid.kol.model.elements.interfaces.SubtextElement;

import java.io.Serializable;

public class SubtextBinder implements Binder<SubtextElement>, Serializable {
    public static final SubtextBinder ONLY = new SubtextBinder();
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 7021656191905202639L;

    private SubtextBinder() {

    }

    @Override
    public int getView() {
        return R.layout.subtext_view;
    }

    @Override
    public void bind(View view, SubtextElement model) {
        ElementBinder.ONLY.bind(view, model);

        TextView subtext = (TextView) view.findViewById(R.id.list_item_subtext);
        subtext.setText(Html.fromHtml(model.getSubtext()));
        subtext.setVisibility((model.getSubtext().length() <= 2) ? View.GONE : View.VISIBLE);
    }

}
