package com.starfish.kol.model.models.chat.actions;

import com.starfish.kol.model.elements.interfaces.DeferredAction;
import com.starfish.kol.model.models.chat.ChatModel;

public class SetCurrentRoomAction implements DeferredAction<ChatModel>{
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -817684091748289682L;
	private final String room;
	public SetCurrentRoomAction(String room) {
		this.room = room;
	}
	
	@Override
	public void submit(ChatModel context) {
		context.setCurrentRoom(room);
	}

}
