package com.starfish.kol.model.models.inventory;

import java.util.ArrayList;

import com.starfish.kol.model.basic.ActionItem;
import com.starfish.kol.model.basic.BasicSubtextItem;

public class InventoryItem extends BasicSubtextItem {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 8203542965489207042L;

	private final ArrayList<ActionItem> actions;

	public InventoryItem(String name, String url, ArrayList<ActionItem> actions) {
		super(name, url);
		this.actions = actions;
	}

	public InventoryItem(String name, String url, String subtext,
			ArrayList<ActionItem> actions) {
		super(name, url, subtext);
		this.actions = actions;
	}

	public ArrayList<ActionItem> getActions() {
		return actions;
	}
}
