package com.starfish.kol.model.models;

import com.starfish.kol.connection.ServerReply;
import com.starfish.kol.connection.Session;

public abstract class FilteredWebModel extends WebModel {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -2252578234021924109L;
	
	public FilteredWebModel(Session s, ServerReply text) {
		super(s, text);
		
		this.setHTML(filterHtml(text.html));
	}
	
	protected abstract String filterHtml(String html);
}
