package com.starfish.kol.model.models;

import java.util.ArrayList;

import com.starfish.kol.connection.ServerReply;
import com.starfish.kol.connection.Session;
import com.starfish.kol.model.LiveModel;
import com.starfish.kol.model.elements.ActionElement;

public class NavigationModel extends LiveModel {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 1037526493595536003L;

	private ArrayList<ActionElement> locations;

	public NavigationModel(Session session) {
		super(session, "topmenu.php", false);

		this.locations = new ArrayList<ActionElement>();
		loadContent(null);
	}

	private void conditionalAdd(String html, String name, String image,
			String... urls) {
		for (String url : urls) {
			if (html.contains(url)) {
				locations.add(new ActionElement(getSession(), name, image, url));
				break;
			}
		}
	}

	public ArrayList<ActionElement> getLocations() {
		this.access();
		return new ArrayList<ActionElement>(this.locations);
	}

	@Override
	protected void loadContent(ServerReply content) {
		this.locations.clear();

		locations.add(new ActionElement(getSession(), "Main Map",
				"http://images.kingdomofloathing.com/itemimages/map.gif",
				"main.php"));
		locations.add(new ActionElement(getSession(), "Inventory",
				"http://images.kingdomofloathing.com/itemimages/backpack.gif",
				"inventory.php"));
		locations.add(new ActionElement(getSession(), "Skills",
				"http://images.kingdomofloathing.com/itemimages/book3.gif",
				"skills.php"));
		locations.add(new ActionElement(getSession(), "Crafting",
				"http://images.kingdomofloathing.com/itemimages/pliers.gif",
				"craft.php"));

		if (content != null) {
			String html = content.html;
			conditionalAdd(
					html,
					"Seaside Town",
					"http://images.kingdomofloathing.com/itemimages/seasidetown.gif",
					"town.php", "whichplace=town");
			conditionalAdd(html, "Your Campsite",
					"http://images.kingdomofloathing.com/itemimages/tent1.gif",
					"campground.php", "place.php?whichplace=campground");
			conditionalAdd(
					html,
					"The Big Mountains",
					"http://images.kingdomofloathing.com/itemimages/themountains.gif",
					"mountains.php", "place.php?whichplace=mountains");
			conditionalAdd(
					html,
					"The Sea",
					"http://images.kingdomofloathing.com/itemimages/thesea.gif",
					"thesea.php", "place.php?whichplace=thesea");
			conditionalAdd(
					html,
					"The Plains",
					"http://images.kingdomofloathing.com/itemimages/theplains.gif",
					"plains.php", "place.php?whichplace=plains");
			conditionalAdd(
					html,
					"Desert Beach",
					"http://images.kingdomofloathing.com/itemimages/thedesert.gif",
					"beach.php", "place.php?whichplace=desertbeach");
			conditionalAdd(
					html,
					"The Distant Woods",
					"http://images.kingdomofloathing.com/itemimages/bansai.gif",
					"woods.php", "place.php?whichplace=woods");

			conditionalAdd(
					html,
					"The Mysterious Island of Mystery",
					"http://images.kingdomofloathing.com/itemimages/theisland.gif",
					"island.php", "place.php?whichplace=island");
			conditionalAdd(
					html,
					"Your Clan Hall",
					"http://images.kingdomofloathing.com/itemimages/clanhall.gif",
					"clan_hall.php", "place.php?whichplace=clan");

			conditionalAdd(
					html,
					"The Mall",
					"http://images.kingdomofloathing.com/itemimages/themall.gif",
					"mall.php");
			
			conditionalAdd(
					html,
					"The Beanstalk",
					"http://images.kingdomofloathing.com/itemimages/thebeanstalk.gif",
					"beanstalk.php", "place.php?whichplace=beanstalk");

			conditionalAdd(
					html,
					"Sorceress' Lair",
					"http://images.kingdomofloathing.com/itemimages/lairicon.gif",
					"lair.php", "place.php?whichplace=lair");
			conditionalAdd(
					html,
					"Spookyraven Manor",
					"http://images.kingdomofloathing.com/itemimages/manoricon.gif",
					"place.php?whichplace=manor1", "place.php?whichplace=manor1");
			conditionalAdd(
					html,
					"PvP",
					"http://images.kingdomofloathing.com/itemimages/swords.gif",
					"peevpee.php");
		}

		locations.add(new ActionElement(getSession(), "Messages",
				"http://images.kingdomofloathing.com/itemimages/envelope.gif",
				"messages.php"));
		locations.add(new ActionElement(getSession(), "Donate",
				"http://images.kingdomofloathing.com/itemimages/donate.gif",
				"donatepopup.php"));
		locations
				.add(new ActionElement(getSession(), 
						"Options",
						"http://images.kingdomofloathing.com/itemimages/blackwrench.gif",
						"account.php"));
		locations.add(new ActionElement(getSession(), "Community",
				"http://images.kingdomofloathing.com/itemimages/chat.gif",
				"community.php"));
		locations.add(new ActionElement(getSession(), "Help",
				"http://images.kingdomofloathing.com/itemimages/help.gif",
				"doc.php?topic=home"));
		locations.add(new ActionElement(getSession(), "Report Bug",
				"http://images.kingdomofloathing.com/itemimages/beetle.gif",
				"adminmail.php"));
		locations.add(new ActionElement(getSession(), "Logout",
				"http://images.kingdomofloathing.com/itemimages/sleepy.gif",
				"logout.php"));
	}
}
