package com.starfish.kol.model.models;

import java.util.ArrayList;

import com.starfish.kol.connection.Connection.ServerReply;
import com.starfish.kol.connection.Session;
import com.starfish.kol.model.Model;
import com.starfish.kol.model.elements.OptionElement;
import com.starfish.kol.model.elements.basic.BasicAction;
import com.starfish.kol.model.elements.basic.BasicGroup;
import com.starfish.kol.model.elements.basic.BasicElement;
import com.starfish.kol.model.elements.interfaces.DeferredGameAction;
import com.starfish.kol.model.elements.interfaces.ModelGroup;
import com.starfish.kol.model.elements.interfaces.MultiUseableItem;
import com.starfish.kol.model.elements.interfaces.SubtextItem;
import com.starfish.kol.util.Regex;

public class SkillsModel extends Model<Void> {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 295714863597L;

	private static final Regex RESULTS_PANE = new Regex(
			"<table[^>]*>.*?Results:.*?</table>", 0);
	private static final Regex PAGE_BODY = new Regex(
			"(<body[^>]*>)(.*?)(</body>)", 2);
	private String resultsPane;

	private static final Regex ITEMS_FORM = new Regex(
			"<form[^>]*restorerform[^>]*>.*?</form>", 0);
	
	private static final Regex SKILLS_FORM = new Regex(
			"<form[^>]*skillform[^>]*>.*?</form>", 0);
	private static final Regex BUFFS_FORM = new Regex("<form[^>]*buffform[^>]*>.*?</form>", 0);
	private static final Regex BUFFS_LIST = OptionElement.regexFor("whichskill");
	
	private static final Regex PWD = new Regex("<input[^>]*pwd[^>]*>", 0);
	private static final Regex EXTRACT_VALUE = new Regex(
			"value=[\"']?([0-9a-fA-F]*)", 1);
	
	private static final Regex OPTION_MP = new Regex("\\(.*?\\)", 0);
	
	private static final Regex OPTION_YOURSELF = new Regex("<option value=[\"']?(\\d+)[\"']?>\\(yourself\\)</option>", 1);

	private final ArrayList<RestorerItem> items;
	private final ArrayList<ModelGroup<SkillItem>> skills;

	private final boolean usedItem;
	public SkillsModel(Session s, ServerReply text) {
		super(s, text);
		this.loadContent(text);

		this.skills = processSkills(text.html);
		this.items = processItems(text.html);
		usedItem = text.url.contains("useditem");
	}
	
	private ArrayList<RestorerItem> processItems(String html) {
		ArrayList<RestorerItem> items = new ArrayList<RestorerItem>();

		String all_items = ITEMS_FORM.extractSingle(html);
		System.out.println(all_items);
		String pwd = EXTRACT_VALUE.extractSingle(PWD.extractSingle(all_items));
		String actionBase = "inv_use.php?pwd=" + pwd + "&action=useitem&bounce=skills.php%3Faction%3Duseditem";
		
		ArrayList<OptionElement> options = OptionElement.extractOptions(all_items);
		for(OptionElement option : options) {
			items.add(new RestorerItem(option.text, actionBase + "&whichitem=" + option.value));
		}
		
		return items;
	}
	
	private ArrayList<ModelGroup<SkillItem>> processSkills(String html) {
		ArrayList<ModelGroup<SkillItem>> skills = new ArrayList<ModelGroup<SkillItem>>();

		String all_skills = SKILLS_FORM.extractSingle(html);
		String pwd = EXTRACT_VALUE.extractSingle(PWD.extractSingle(all_skills));
		String actionBase = "skills.php?pwd=" + pwd + "&action=Skillz";

		ArrayList<ModelGroup<OptionElement>> options = OptionElement.extractOptionGroups(all_skills, "Skills");
		System.out.println(all_skills);
		System.out.println("Found " + options.size() + " skill options");
		for(ModelGroup<OptionElement> optiongroup : options) {
			BasicGroup<SkillItem> group = new BasicGroup<SkillItem>(optiongroup.getName());
			System.out.println("Found group with " + options.size() + " skills");
			for(OptionElement option : optiongroup) {
				if(option.text.contains("(select a skill)")) continue;
				
				SkillItem skill = processSkill(option, actionBase, false);
				group.add(skill);
			}
			skills.add(group);
		}
		
		
		String all_buffs = BUFFS_LIST.extractSingle(BUFFS_FORM.extractSingle(html));
		String yourself = OPTION_YOURSELF.extractSingle(all_buffs);
		pwd = EXTRACT_VALUE.extractSingle(PWD.extractSingle(all_buffs));
		actionBase = "skills.php?pwd=" + pwd + "&action=Skillz&targetplayer=" + yourself;
		ArrayList<OptionElement> buffsoptions = OptionElement.extractOptions(all_buffs);
		BasicGroup<SkillItem> buffs = new BasicGroup<SkillItem>("Buffs");
		for(OptionElement option : buffsoptions) {
			if(option.text.contains("(select a buff)")) continue;
			
			SkillItem skill = processSkill(option, actionBase, true);
			buffs.add(skill);
		}
		skills.add(buffs);
		
		return skills;
	}

	private SkillItem processSkill(OptionElement option, String actionBase,
			boolean isBuff) {
		String name = option.text;
		String subtext = OPTION_MP.extractSingle(name); // mp cost of skill
		if(subtext == null)
			subtext = "";

		name = OPTION_MP.replaceAll(name, ""); // remove mp from skill name
		return new SkillItem(name, subtext, actionBase + "&whichskill=" + option.value, option.disabled, isBuff);
	}

	protected boolean loadContent(ServerReply text) {
		if (!text.url.contains("skills.php")) {
			System.out
					.println("Attempted to load non-skill page into SkillModel: "
							+ text.url);
			return false;
		}

		resultsPane = RESULTS_PANE.extractSingle(text.html);

		return true;
	}

	public WebModel getResultsPane() {
		if (resultsPane == null)
			return null;

		ServerReply base = this.getBase();
		String html = PAGE_BODY.replaceAll(base.html, "$1<center>"
				+ resultsPane + "</center>$3");
		ServerReply newRep = new ServerReply(base.responseCode,
				base.redirectLocation, base.date, html, "small/skillresults.php",
				base.cookie);
		return new WebModel(getSession(), newRep);
	}

	public ArrayList<ModelGroup<SkillItem>> getSkills() {
		return this.skills;
	}

	public ArrayList<RestorerItem> getRestorers() {
		return this.items;
	}

	public boolean getJustUsedItem() {
		return usedItem;
	}

	public class RestorerItem extends BasicElement implements MultiUseableItem{
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 2931087678941136636L;

		private final String actionBase;
		
		public RestorerItem(String text, String actionBase) {
			super(text);
			this.actionBase = actionBase;
		}
		
		public RestorerItem(String text, String img, String actionBase) {
			super(text, img);
			this.actionBase = actionBase;
		}
		
		public DeferredGameAction use(String quantity) {
			String action = actionBase + "&itemquantity=" + quantity;
			return new BasicAction(getSession(), action);
		}
		
	}
	
	public class SkillItem extends BasicElement implements SubtextItem {
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 7468444853147077407L;

		private final String subtext;
		private final boolean disabled;
		private final String actionBase;
		private final boolean buff;

		public SkillItem(String name, String subtext, String actionBase,
				boolean disabled, boolean buff) {
			super(name, null);

			this.subtext = subtext;
			this.actionBase = actionBase;
			this.disabled = disabled;
			this.buff = buff;
		}

		public String getSubtext() {
			return subtext;
		}

		public boolean getIsDisabled() {
			return disabled;
		}
		
		public boolean isBuff() {
			return buff;
		}
		
		public DeferredGameAction cast(String number, String onPlayer) {
			String action = actionBase;
			if(buff) {
				//do something with onPlayer
				action += "&specificplayer=" + onPlayer;
				action += "&bufftimes=" + number;
			} else {
				action += "&quantity=" + number;
			}
			
			return new BasicAction(getSession(), action);
		}
	}

	public static enum SkillsMessage {
		REFRESH
	}
}
