package com.github.kolandroid.kol.model.elements;

import com.github.kolandroid.kol.connection.Session;
import com.github.kolandroid.kol.model.elements.basic.BasicAction;
import com.github.kolandroid.kol.model.elements.interfaces.DeferredGameAction;
import com.github.kolandroid.kol.model.elements.interfaces.Multiuseable;
import com.github.kolandroid.kol.model.elements.interfaces.SubtextElement;

public class MultiuseElement implements Multiuseable {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 1517694327159233372L;

    private final SubtextElement base;
    private final String useLink;
    private final Session session;

    public MultiuseElement(Session session, SubtextElement base, String useLink) {
        this.session = session;
        this.base = base;
        this.useLink = useLink;
    }

    @Override
    public String getText() {
        return base.getText();
    }

    @Override
    public String getImage() {
        return base.getImage();
    }

    @Override
    public String getSubtext() {
        return base.getSubtext();
    }

    @Override
    public DeferredGameAction use(String quantity) {
        return new BasicAction(session, useLink + quantity);
    }
}
