package com.github.kolandroid.kol.model.models;


import com.github.kolandroid.kol.connection.ServerReply;
import com.github.kolandroid.kol.model.GroupModel;
import com.github.kolandroid.kol.model.LiveModel;
import com.github.kolandroid.kol.session.Session;

public abstract class LiveWebModel extends LiveModel implements GroupModel.ChildModel {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = -7806837522602916575L;

    private final String title;
    private WebModel base;

    public LiveWebModel(Session s, String title, String updateUrl) {
        super(s, updateUrl, true);
        this.base = new WebModel(getSession(), new ServerReply(200, "", "", "", "", ""));
        this.title = title;
    }

    @Override
    protected void loadContent(ServerReply content) {
        ServerReply newRep = new ServerReply(content.responseCode,
                content.redirectLocation, content.date, correctHtml(content.html), content.url,
                content.cookie);
        this.base = new WebModel(getSession(), newRep);
    }

    public abstract String correctHtml(String html);

    public String getTitle() {
        return title;
    }

    public WebModel getBaseModel() {
        this.access();
        return base;
    }

}