package com.starfish.kol.connection;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Serializable;
import java.io.StringWriter;
import java.net.HttpURLConnection;

public class ServerReply implements Serializable {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -7171484980493452228L;

	public final int responseCode;
	public final String redirectLocation;
	public final String date;
	public final String url;
	public final String cookie;

	public final String html;

	public ServerReply(int responseCode, String redirectLocation, String date,
			String html, String url, String cookie) {
		this.responseCode = responseCode;
		this.redirectLocation = redirectLocation;
		this.date = date;
		this.html = html;
		this.url = url;
		this.cookie = cookie;
	}

	protected ServerReply(HttpURLConnection base) throws IOException {
		responseCode = base.getResponseCode();
		redirectLocation = (responseCode / 100 == 3) ? base
				.getHeaderField("Location") : null;

		url = base.getURL().toString();
		date = base.getHeaderField("Date");
		cookie = getCookie(base);

		this.html = getResponse(base);

	}

	public ServerReply(ServerReply prototype, String html) {
		this.responseCode = prototype.responseCode;
		this.redirectLocation = prototype.redirectLocation;
		this.date = prototype.date;
		this.url = prototype.url;
		this.cookie = prototype.cookie;

		this.html = html;
	}

	private static String getResponse(HttpURLConnection base)
			throws IOException {
		InputStream is = base.getInputStream();
		if (is == null)
			return "";

		try {
			StringWriter sw = new StringWriter();

			BufferedReader r = new BufferedReader(new InputStreamReader(is));
			String s;

			while ((s = r.readLine()) != null) {
				sw.append(s + '\n');
			}

			r.close();
			return sw.toString();
		} catch (IOException e) {
			throw e;
		}
	}

	private static String getCookie(HttpURLConnection base) {
		String cookies = "";
		for (int i = 0;; i++) {
			if (base.getHeaderField(i) == null)
				break;

			if ("Set-Cookie".equals(base.getHeaderFieldKey(i))) {
				if (cookies.length() > 0)
					cookies += "; ";
				cookies += base.getHeaderField(i);
			}
		}
		return cookies;
	}

	@Override
	public String toString() {
		String s = "RESPONSE CODE: " + responseCode;
		if (responseCode / 100 == 3)
			s += "\nREDIRECT: " + redirectLocation;
		s += "\nRESULT: " + html;
		return s;
	}
}