package com.starfish.kol.android.game.fragments.inventory;

import android.annotation.SuppressLint;
import android.os.Bundle;
import android.support.v4.app.DialogFragment;
import android.support.v4.app.FragmentTransaction;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;

import com.starfish.kol.android.R;
import com.starfish.kol.android.dialogs.ItemDialog;
import com.starfish.kol.android.game.BaseGameFragment;
import com.starfish.kol.android.util.listbuilders.SubtextBuilder;
import com.starfish.kol.android.util.searchlist.GroupSearchListFragment;
import com.starfish.kol.android.util.searchlist.SerializableSelector;
import com.starfish.kol.model.basic.ActionItem;
import com.starfish.kol.model.models.inventory.EquipmentPocketModel;
import com.starfish.kol.model.models.inventory.InventoryItem;
import com.starfish.kol.model.util.LiveModel.LiveMessage;

@SuppressLint("ValidFragment")
public class EquipmentPaneFragment extends BaseGameFragment<LiveMessage, EquipmentPocketModel> {
	public EquipmentPaneFragment() {
		super(R.layout.fragment_equipment_pane);
	}

	private GroupSearchListFragment<InventoryItem> listfrag;
	
	@Override
	public void onCreateSetup(View view, EquipmentPocketModel base,
			Bundle savedInstanceState) {
		listfrag = GroupSearchListFragment.newInstance("", base.getItems(), new SubtextBuilder<InventoryItem>(), displayPossibleActions);
		FragmentTransaction trans = getChildFragmentManager().beginTransaction().replace(R.id.inventory_list, listfrag);
		trans.commit();
		
		Button equipoutfit = (Button)view.findViewById(R.id.equipment_equipoutfit);
		equipoutfit.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View arg0) {
				GroupSearchListFragment<ActionItem> outfitfragment = GroupSearchListFragment.newInstance("Equip outfit", getModel().getOutfits());
				outfitfragment.show(getFragmentManager(), "outfits");
			}			
		});
	}

	@Override
	protected void recieveProgress(LiveMessage message) {
		if(listfrag != null)
			listfrag.setItems(getModel().getItems());
		
	}
	
	private static final SerializableSelector<InventoryItem> displayPossibleActions = new SerializableSelector<InventoryItem>(){
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 6502795666816716450L;

		@Override
		public boolean selectItem(DialogFragment list, InventoryItem item) {
			ItemDialog.create(item).show(list.getFragmentManager(), "itemoptions");
			return true;
		}		
	};

}
