package com.starfish.kol.android.game.fragments.inventory;

import android.annotation.SuppressLint;
import android.os.Bundle;
import android.support.v4.app.DialogFragment;
import android.support.v4.app.FragmentTransaction;
import android.view.View;

import com.starfish.kol.android.R;
import com.starfish.kol.android.dialogs.ItemDialog;
import com.starfish.kol.android.game.GameFragment;
import com.starfish.kol.android.util.listbuilders.SubtextBuilder;
import com.starfish.kol.android.util.searchlist.GroupSearchListFragment;
import com.starfish.kol.android.util.searchlist.SerializableSelector;
import com.starfish.kol.model.LiveMessage;
import com.starfish.kol.model.models.inventory.InventoryItem;
import com.starfish.kol.model.models.inventory.InventoryPocketModel;

@SuppressLint("ValidFragment")
public class InventoryPaneFragment extends GameFragment<LiveMessage, InventoryPocketModel> {
	public InventoryPaneFragment() {
		super(R.layout.fragment_inventory_pane);
	}
	
	protected InventoryPaneFragment(int layoutid) {
		super(layoutid);
	}

	private GroupSearchListFragment<InventoryItem> listfrag;
	
	@Override
	public void onCreateSetup(View view, InventoryPocketModel base,
			Bundle savedInstanceState) {
		listfrag = GroupSearchListFragment.newInstance("", base.getItems(), new SubtextBuilder<InventoryItem>(), displayPossibleActions);
		FragmentTransaction trans = getChildFragmentManager().beginTransaction().replace(R.id.inventory_list, listfrag);
		trans.commit();		
	}

	@Override
	protected void recieveProgress(LiveMessage message) {
		if(listfrag != null)
			listfrag.setItems(getModel().getItems());
		
	}
	
	private static final SerializableSelector<InventoryItem> displayPossibleActions = new SerializableSelector<InventoryItem>(){
		/**
		 * Autogenerated by eclipse.
		 */
		private static final long serialVersionUID = 6502795666816716450L;

		@Override
		public boolean selectItem(DialogFragment list, InventoryItem item) {
			ItemDialog.create(item).show(list.getFragmentManager(), "itemoptions");
			return true;
		}		
	};

}
