package com.starfish.kol.model.interfaces;




public class SimpleItem implements ModelItem
{
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 8834750738130793384L;
	
	private String text;
	private String img;
	
	public SimpleItem(String text) {
		this(text, "");
	}

	public SimpleItem(String text, String img) {
		this.text = text;
		this.img = img;
	}
	
	@Override
	public String getText() {
		return this.text;
	}

	@Override
	public String getImage() {
		return this.img;
	}

	@Override
	public String toString() {
		return this.text;
	}
}
