package com.github.kolandroid.kol.android.controllers.inventory;

import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;

import com.github.kolandroid.kol.android.R;
import com.github.kolandroid.kol.android.controller.Controller;
import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.android.screen.ScreenSelection;
import com.github.kolandroid.kol.model.elements.interfaces.DeferredGameAction;
import com.github.kolandroid.kol.model.models.inventory.EquipmentPocketModel.CustomOutfitBuilder;

public class CustomOutfitController implements Controller {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = -7098637980143983599L;

    private final CustomOutfitBuilder base;

    public CustomOutfitController(CustomOutfitBuilder base) {
        this.base = base;
    }

    @Override
    public int getView() {
        return R.layout.save_outfit_view;
    }

    @Override
    public void connect(View view, final Screen host) {
        final EditText nameEdit = (EditText) view.findViewById(R.id.save_outfit_input);
        Button submit = (Button) view.findViewById(R.id.save_outfit_submit);
        submit.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View arg0) {
                String name = nameEdit.getText().toString();
                if (name.equals("")) return;

                DeferredGameAction action = base.saveOutfit(name);
                action.submit(host.getViewContext());
                host.close();
            }
        });
    }

    @Override
    public void disconnect(Screen host) {
        // do nothing
    }

    @Override
    public void chooseScreen(ScreenSelection choice) {
        choice.displayDialog(this);
    }

}
