package com.starfish.kol.android.util.searchlist;

import android.support.v4.app.DialogFragment;

import com.starfish.kol.android.view.ApplicationView;
import com.starfish.kol.model.basic.ActionItem;

public class ActionSelector<E extends ActionItem> implements OnListSelection<E>{
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 3523297469606009532L;

	@Override
	public boolean selectItem(DialogFragment list, E item) {
		ApplicationView app = (ApplicationView)list.getActivity().getApplication();
		app.executeAction(item);
		return true;
	}
}