package com.starfish.kol.android.util.searchlist;

import java.io.Serializable;

import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.gamehandler.ViewContext;
import com.starfish.kol.model.elements.ActionElement;

public class ControllerActionSelector<E extends ActionElement> implements ControllerOnListSelection<E>, Serializable{
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 3463753434332L;

	@Override
	public boolean selectItem(Screen list, E item) {		
		item.submit((ViewContext)list.getActivity());
		return true;
	}
}