package com.starfish.kol.android.controller;

import android.view.View;

import com.starfish.kol.android.binders.Binder;
import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.android.screen.ScreenSelection;

public class BinderController<E> implements Controller {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -8821670180432097129L;
	
	private final Binder<? super E> binder;
	private E displayed;
	
	private transient View view;
	
	public BinderController(Binder<? super E> binder, E defaultElem) {
		this.binder = binder;
		this.displayed = defaultElem;
	}
	
	@Override
	public int getView() {
		return binder.getView();
	}

	public E getValue() {
		return displayed;
	}
	
	public void setValue(E toDisplay) {
		this.displayed = toDisplay;
		if(view != null)
			binder.bind(view, toDisplay);
	}
	@Override
	public void connect(View view, Screen host) {
		this.view = view;
		binder.bind(view, displayed);
	}

	@Override
	public void disconnect() {
		view = null;
	}

	@Override
	public void chooseScreen(ScreenSelection choice) {
		choice.displayPrimary(this);
	}

}
