package com.starfish.kol.android.controller;

import java.util.ArrayList;

import android.support.v4.app.DialogFragment;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;

import com.starfish.kol.android.R;
import com.starfish.kol.android.dialogs.FunkslingingDialog;
import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.android.screen.ScreenSelection;
import com.starfish.kol.android.screen.ViewScreen;
import com.starfish.kol.android.util.listbuilders.SubtextBuilder;
import com.starfish.kol.android.util.searchlist.SearchListFragment;
import com.starfish.kol.model.elements.ActionElement;
import com.starfish.kol.model.models.fight.FightItem;
import com.starfish.kol.model.models.fight.FightModel;
import com.starfish.kol.model.models.fight.FightSkill;

public class FightController extends ModelController<Void, FightModel> {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -7848760148015474401L;

	public FightController(FightModel model) {
		super(model);
	}

	@Override
	public int getView() {
		return R.layout.fragment_fight_screen;
	}

	@Override
	public void chooseScreen(ScreenSelection choice) {
		choice.displayPrimary(this);
	}

	@Override
	public void connect(View view, FightModel model, final Screen host) {
		final Button attack = (Button)view.findViewById(R.id.fight_attack);
		attack.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View arg0) {
				ActionElement action = getModel().getAttack();
				if(action != null)
					action.submit(host.getViewContext());
			}
		});
		
		final Button useskill = (Button)view.findViewById(R.id.fight_skill);
		useskill.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View btn) {
				ArrayList<FightSkill> skills = getModel().getSkills();
				SubtextBuilder<FightSkill> builder = new SubtextBuilder<FightSkill>();
				
				SearchListFragment<FightSkill> newFragment = SearchListFragment.newInstance("Choose a skill to use:", builder, skills);
			    newFragment.show(host.getFragmentManager(), "dialog");
			}
		});
		
		final Button useitem = (Button)view.findViewById(R.id.fight_items);
		useitem.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View btn) {
				ArrayList<FightItem> items = getModel().getItems();
				
				DialogFragment newFragment;
				
				if(getModel().hasFunkslinging())
					newFragment = FunkslingingDialog.create(items);
				else
					newFragment = SearchListFragment.newInstance("Choose an item to use:", items);
				
			    newFragment.show(host.getFragmentManager(), "dialog");
			}			
		});
		
		if(model.isFightOver()) {
			attack.setEnabled(false);
			useskill.setEnabled(false);
			useitem.setEnabled(false);
		}
		
		ViewScreen webscreen = (ViewScreen)view.findViewById(R.id.fight_webscreen);
		WebController web = new WebController(model);
		webscreen.display(web, host);
	}

}
