package com.starfish.kol.android.controller;

import android.support.v4.app.Fragment;
import android.view.View;

import com.starfish.kol.android.R;
import com.starfish.kol.android.screen.FragmentScreen;
import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.android.util.CustomFragmentTabHost;
import com.starfish.kol.android.util.CustomFragmentTabHost.OnCreateFragmentListener;
import com.starfish.kol.model.GroupModel;
import com.starfish.kol.model.GroupModel.ChildModel;

public abstract class LinkedGroupController<C extends ChildModel, M extends GroupModel<C>> extends GroupController<C, M> {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 3395000588012861100L;

	public LinkedGroupController(M model) {
		super(model);
	}

	protected abstract UpdatableController<C> getController(C child);
	protected abstract void linkChild(UpdatableController<C> controller, String tag);

	@Override
	public void connect(View view, M model, Screen host) {
		super.connect(view, model, host);
		final CustomFragmentTabHost tabHost = (CustomFragmentTabHost) view
				.findViewById(R.id.tabs_tabhost);
		tabHost.setOnCreateFragmentListener(new OnCreateFragmentListener() {
			@SuppressWarnings("unchecked")
			@Override
			public void setup(Fragment f, String tag) {
				FragmentScreen screen = (FragmentScreen)f;
				UpdatableController<C> controller = (UpdatableController<C>)screen.getController();
				linkChild(controller, tag);
			}			
		});
	}
}
