package com.starfish.kol.android.controller;

import android.view.View;

import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.model.Model;

public abstract class ModelController<M extends Model> implements Controller {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 5761904333216584549L;
	
	private M model;
	
	public ModelController(M model) {
		this.model = model;
	}
	
	@Override
	public void connect(final View view, final Screen host) {		
		this.model.attachView(host.getViewContext());
		this.connect(view, model, host);
	}
	
	public abstract void connect(View view, M model, Screen host);
	
	@Override
	public void disconnect(Screen host) {
		// do nothing
	}

	protected void setModel(M model) {
		this.model = model;
	}
	
	public M getModel() {
		return model;
	}
}
