package com.starfish.kol.android.controller;

import android.view.View;
import android.view.View.OnClickListener;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.android.screen.ScreenSelection;
import com.starfish.kol.android.util.ProgressBar;
import com.starfish.kol.model.LiveMessage;
import com.starfish.kol.model.models.StatsModel;

public class StatsController extends ModelController<LiveMessage, StatsModel> {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -5515046804414654496L;
	
	public StatsController(StatsModel model) {
		super(model);
	}
		
	@Override
	public int getView() {
		return R.layout.fragment_stats_small;
	}

	@Override
	public void connect(View view, final StatsModel model, Screen host) {
		view.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View arg0) {
				model.loadFull();
			}
		});

		StatsCallbacks activity = (StatsCallbacks)host.getActivity();
		activity.register(this);
		
		this.refresh();
	}

	public void recieveProgress(View view, StatsModel model, LiveMessage message, Screen host) {
		StatsCallbacks activity = (StatsCallbacks)host.getActivity();
		if(activity != null) {
			activity.update(model.getUsername(), model.getCharInfo());
		}
		
		TextView txtMuscle = (TextView) view.findViewById(R.id.stats_small_muscle);
		String muscle = model.getMuscle() + " (" + model.getMuscleBase() + ")";
		txtMuscle.setText(muscle);
		
		TextView txtMyst = (TextView) view.findViewById(R.id.stats_small_myst);
		String myst = model.getMyst() + " (" + model.getMystBase() + ")";
		txtMyst.setText(myst);

		TextView txtMoxie = (TextView) view.findViewById(R.id.stats_small_moxie);
		String moxie = model.getMoxie() + " (" + model.getMoxieBase() + ")";
		txtMoxie.setText(moxie);

		ProgressBar barHP = (ProgressBar) view.findViewById(R.id.stats_small_hp);
		barHP.setProgress(model.getHP(), model.getHPBase());
		
		ProgressBar barMP = (ProgressBar) view.findViewById(R.id.stats_small_mp);
		barMP.setProgress(model.getMP(), model.getMPBase());

		TextView txtAdv = (TextView) view.findViewById(R.id.stats_small_adv);
		txtAdv.setText(model.getAdv() + "");
		
		TextView txtMeat = (TextView) view.findViewById(R.id.stats_small_meat);
		txtMeat.setText(model.getMeat() + "");
	}
	
	public void refresh() {
		getModel().update();
	}
	
	public void showQuests() {
		getModel().loadQuests();
	}
	
	public static interface StatsCallbacks {
		public void update(String username, String subtext);
		public void register(StatsController statController);
	}

	@Override
	public void chooseScreen(ScreenSelection choice) {
		choice.displayPrimary(this);
	}
}
