package com.starfish.kol.android.controllers;

import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.android.controller.Controller;
import com.starfish.kol.android.screen.Screen;
import com.starfish.kol.android.screen.ScreenSelection;
import com.starfish.kol.android.util.ImageDownloader;
import com.starfish.kol.model.elements.interfaces.DeferredGameAction;
import com.starfish.kol.model.elements.interfaces.Multiuseable;

public class MultiusableController implements Controller {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = -6555855723943818170L;
	
	private final Multiuseable base;
	private final String useText;
	
	public MultiusableController(Multiuseable base, String useText) {
		this.base = base;
		this.useText = useText;
	}
	
	@Override
	public int getView() {
		return R.layout.dialog_multiuse_screen;
	}

	@Override
	public void connect(final View view, final Screen host) {
		TextView text = (TextView) view
				.findViewById(R.id.dialog_multiuse_name);
		text.setText(base.getText());

		ImageView img = (ImageView) view
				.findViewById(R.id.dialog_multiuse_image);
		if (base.getImage() == null || base.getImage().length() == 0) {
			img.setVisibility(View.GONE);
		} else {
			img.setVisibility(View.VISIBLE);
			ImageDownloader.loadFromUrl(img, base.getImage());
		}

		Button submit = (Button) view
				.findViewById(R.id.dialog_multiuse_submit);
		submit.setText(useText);
		
		submit.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View arg0) {
				EditText number = (EditText) view
						.findViewById(R.id.dialog_multiuse_number);

				String num = number.getText().toString();
				if (num == null || num.length() == 0)
					return;

				DeferredGameAction action = base.use(num);
				action.submit(host.getViewContext());
				host.close();
			}
		});
	}

	@Override
	public void disconnect(Screen host) {
		// do nothing
	}

	@Override
	public void chooseScreen(ScreenSelection choice) {
		choice.displayDialog(this);
	}
}
