package com.github.kolandroid.kol.session;

import com.github.kolandroid.kol.util.Regex;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class Session implements Serializable {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 7771874452940822920L;

    private static final Regex COOKIE_FINDER = new Regex("(^|;| )([^ =;]*)=([^ =;]*)(;|$)", 2, 3);

    private final Map<String, String> cookieMap;
    private String allCookies;

    public Session() {
        this.cookieMap = new HashMap<>();
        this.allCookies = "";
    }

    public Session(String cookies) {
        this();
        this.addCookies(cookies);
    }

    public String getCookie() {
        return allCookies;
    }

    public String getCookie(String which, String defaultVal) {
        if (cookieMap.containsKey(which)) {
            return cookieMap.get(which);
        }

        return defaultVal;
    }

    public void removeCookie(String which) {
        if (cookieMap.containsKey(which)) {
            cookieMap.remove(which);
        }
    }

    public void addCookies(String cookies) {
        if (cookies == null) return;

        for (String[] match : COOKIE_FINDER.extractAll(cookies)) {
            if (match[0] != null && match[1] != null) {
                cookieMap.put(match[0], match[1]);
            }
        }

        allCookies = "";
        for (String key : cookieMap.keySet()) {
            allCookies += key + "=" + cookieMap.get(key) + "; ";
        }
    }

    public String getServer() {
        if (cookieMap.containsKey("appserver")) {
            return cookieMap.get("appserver");
        } else {
            return "www";
        }
    }

    @Override
    public String toString() {
        return "$session[" + getCookie() + "]";
    }
}
