package com.github.kolandroid.kol.connection;

import com.github.kolandroid.kol.util.Regex;

import java.io.Serializable;

public class Session implements Serializable {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 7771874452940822920L;

    private static final Regex SERVER = new Regex("appserver=([^;]*)[;$]", 1);

    private String cookie = null;

    public String getCookie() {
        return cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    public String getServer() {
        String server = SERVER.extractSingle(cookie);

        if (server == null)
            return "www";
        else
            return server;
    }

    @Override
    public String toString() {
        return "$Session[" + cookie + "]";
    }
}
