package com.github.kolandroid.kol.android.controllers.skills;

import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.github.kolandroid.kol.android.R;
import com.github.kolandroid.kol.android.controller.ModelController;
import com.github.kolandroid.kol.android.screen.Screen;
import com.github.kolandroid.kol.android.screen.ScreenSelection;
import com.github.kolandroid.kol.model.models.skill.SkillModel;

public class SkillController extends ModelController<SkillModel> {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 8802030177173483415L;

    public SkillController(SkillModel model) {
        super(model);
    }

    @Override
    public int getView() {
        return R.layout.dialog_skill_screen;
    }

    @Override
    public void connect(final View view, SkillModel model, final Screen host) {
        TextView text = (TextView) view.findViewById(R.id.dialog_skill_text);
        text.setText(model.getText());

        TextView subtext = (TextView) view.findViewById(R.id.dialog_skill_subtext);
        subtext.setText(model.getSubtext());

        Button submit = (Button) view.findViewById(R.id.dialog_skill_submit);
        submit.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View arg0) {
                EditText number = (EditText) view.findViewById(R.id.dialog_skill_number);
                EditText player = (EditText) view.findViewById(R.id.dialog_skill_player);

                String num = number.getText().toString();
                String play = player.getText().toString();
                if (num == null || play == null || num.length() == 0)
                    return;
                if (play.equalsIgnoreCase("(yourself)"))
                    play = "";
                getModel().cast(num, play);
                host.close();
            }
        });
    }

    @Override
    public void disconnect(Screen host) {
        // do nothing
    }

    @Override
    public void chooseScreen(ScreenSelection choice) {
        choice.displayDialog(this);
    }

}
