package com.starfish.kol.model.basic;

import com.starfish.kol.model.interfaces.ModelItem;


public class ActionItem extends BasicAction implements ModelItem
{
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 8834750738130793384L;
	
	private String text;
	private String img;
	
	public ActionItem(String text, String action) {
		this(text, "", action);
	}

	public ActionItem(String text, String img, String action) {
		super(action);
		
		this.text = text;
		this.img = img;
	}
	
	@Override
	public String getText() {
		return this.text;
	}

	@Override
	public String getImage() {
		return this.img;
	}
		
	@Override
	public String toString() {
		return this.text;
	}
}
