package com.github.kolandroid.kol.model.elements.basic;

import com.github.kolandroid.kol.connection.Session;
import com.github.kolandroid.kol.gamehandler.ViewContext;
import com.github.kolandroid.kol.model.elements.interfaces.DeferredGameAction;
import com.github.kolandroid.kol.request.Request;

public class BasicAction implements DeferredGameAction {
    /**
     * Autogenerated by eclipse.
     */
    private static final long serialVersionUID = 7965783002773029040L;

    private final String url;
    private final Session session;

    public BasicAction(Session session, String url) {
        this.url = url;
        this.session = session;
    }

    protected void submit(ViewContext context, String urloverride) {
        Request r = new Request(urloverride);
        r.makeAsync(session, context.createLoadingContext(), context.getPrimaryRoute());
    }

    @Override
    public void submit(ViewContext context) {
        submit(context, url);
    }
}
