package com.starfish.kol.android.binders;

import java.io.Serializable;

import android.text.Html;
import android.view.View;
import android.widget.TextView;

import com.starfish.kol.android.R;
import com.starfish.kol.model.elements.interfaces.SubtextElement;

public class SubtextBinder implements Binder<SubtextElement>, Serializable {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 7021656191905202639L;
	
	public static final SubtextBinder ONLY = new SubtextBinder();
	
	private SubtextBinder() {
		
	}
	
	@Override
	public int getView() {
		return R.layout.list_subtext_item;
	}

	@Override
	public void bind(View view, SubtextElement model) {
		ElementBinder.ONLY.bind(view, model);

		TextView subtext = (TextView) view.findViewById(R.id.list_item_subtext);
		subtext.setText(Html.fromHtml(model.getSubtext()));
		subtext.setVisibility((model.getSubtext().length() <= 2) ? View.GONE : View.VISIBLE);
	}

}
