package com.starfish.kol.android.binders;

import java.io.Serializable;

import android.text.Html;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.starfish.kol.android.R;

public class TextBinder implements Binder<Object>, Serializable {
	/**
	 * Autogenerated by eclipse.
	 */
	private static final long serialVersionUID = 5777375171095970607L;

	public static final TextBinder ONLY = new TextBinder();
	
	private TextBinder() {
		
	}
	
	@Override
	public int getView() {
		return R.layout.list_generic_item;
	}

	@Override
	public void bind(View view, Object model) {
		TextView text = (TextView)view.findViewById(R.id.list_item_text);
		text.setText(Html.fromHtml(model.toString()));
		
		ImageView img = (ImageView)view.findViewById(R.id.list_item_image);
		img.setVisibility(View.GONE);
	}
}
